language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
python:
- '3.6'
install:
- sudo pip install -U pip setuptools
- sudo pip install -r requirements.txt
- sudo pip install coveralls
script:
- ./version.sh
- sudo coverage run --source=dops unitest.py
after_success:
- coveralls
notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=44165bfe5a0ec5c828993958f4c981423d8ff5e1c41c98a99c80b1834eee98b1