language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
python:
- '3.6'
install:
- pip install -U pip setuptools
- pip install -r requirements.txt
- pip install coveralls
script:
- ./version.sh
- python setup.py install
- sudo coverage run --source=dops unitest.py
after_success:
- coveralls