language: python
sudo: required
dist: trusty
group: deprecated-2017Q4
python:
- '3.6'
install:
- sudo pip install -U pip setuptools
- sudo pip install -r requirements.txt
- sudo pip install coveralls
script:
- ./version.sh
- sudo python3 setup.py install
- sudo coverage run --source=dops unitest.py
after_success:
- coveralls